/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.2.dev3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdPlanetsPlanetIdOkLinks', 'model/GetCharactersCharacterIdPlanetsPlanetIdOkPins', 'model/GetCharactersCharacterIdPlanetsPlanetIdOkRoutes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdPlanetsPlanetIdOkLinks'), require('./GetCharactersCharacterIdPlanetsPlanetIdOkPins'), require('./GetCharactersCharacterIdPlanetsPlanetIdOkRoutes'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdOk = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdOkLinks, root.EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdOkPins, root.EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdOkRoutes);
  }
}(this, function(ApiClient, GetCharactersCharacterIdPlanetsPlanetIdOkLinks, GetCharactersCharacterIdPlanetsPlanetIdOkPins, GetCharactersCharacterIdPlanetsPlanetIdOkRoutes) {
  'use strict';




  /**
   * The GetCharactersCharacterIdPlanetsPlanetIdOk model module.
   * @module model/GetCharactersCharacterIdPlanetsPlanetIdOk
   * @version 0.3.2.dev3
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdPlanetsPlanetIdOk</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdPlanetsPlanetIdOk
   * @class
   * @param links {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkLinks>} links array
   * @param pins {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkPins>} pins array
   * @param routes {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkRoutes>} routes array
   */
  var exports = function(links, pins, routes) {
    var _this = this;

    _this['links'] = links;
    _this['pins'] = pins;
    _this['routes'] = routes;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdPlanetsPlanetIdOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdPlanetsPlanetIdOk} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdPlanetsPlanetIdOk} The populated <code>GetCharactersCharacterIdPlanetsPlanetIdOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [GetCharactersCharacterIdPlanetsPlanetIdOkLinks]);
      }
      if (data.hasOwnProperty('pins')) {
        obj['pins'] = ApiClient.convertToType(data['pins'], [GetCharactersCharacterIdPlanetsPlanetIdOkPins]);
      }
      if (data.hasOwnProperty('routes')) {
        obj['routes'] = ApiClient.convertToType(data['routes'], [GetCharactersCharacterIdPlanetsPlanetIdOkRoutes]);
      }
    }
    return obj;
  }

  /**
   * links array
   * @member {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkLinks>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * pins array
   * @member {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkPins>} pins
   */
  exports.prototype['pins'] = undefined;
  /**
   * routes array
   * @member {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdOkRoutes>} routes
   */
  exports.prototype['routes'] = undefined;



  return exports;
}));


