/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.2.dev3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetFleetsFleetIdOk();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetFleetsFleetIdOk', function() {
    it('should create an instance of GetFleetsFleetIdOk', function() {
      // uncomment below and update the code to test GetFleetsFleetIdOk
      //var instane = new EveSwaggerInterface.GetFleetsFleetIdOk();
      //expect(instance).to.be.a(EveSwaggerInterface.GetFleetsFleetIdOk);
    });

    it('should have the property isFreeMove (base name: "is_free_move")', function() {
      // uncomment below and update the code to test the property isFreeMove
      //var instane = new EveSwaggerInterface.GetFleetsFleetIdOk();
      //expect(instance).to.be();
    });

    it('should have the property isRegistered (base name: "is_registered")', function() {
      // uncomment below and update the code to test the property isRegistered
      //var instane = new EveSwaggerInterface.GetFleetsFleetIdOk();
      //expect(instance).to.be();
    });

    it('should have the property isVoiceEnabled (base name: "is_voice_enabled")', function() {
      // uncomment below and update the code to test the property isVoiceEnabled
      //var instane = new EveSwaggerInterface.GetFleetsFleetIdOk();
      //expect(instance).to.be();
    });

    it('should have the property motd (base name: "motd")', function() {
      // uncomment below and update the code to test the property motd
      //var instane = new EveSwaggerInterface.GetFleetsFleetIdOk();
      //expect(instance).to.be();
    });

  });

}));
